// Phase-1 development fixture. Phase 2+ writes from YTM sync directly.
import type { Track } from '../lib/types';

export const SAMPLE_TRACKS: Track[] = [
  {
    id: 'track-01',
    title: 'Hollow Light',
    artist: 'The Long Distance',
    album: 'Aurora, Slow',
    year: 2024,
    duration: 218,
    glyph: 'H',
    palette: { bg: [28, 32, 56], bg2: [86, 52, 130], accent: [235, 188, 255] },
    lyrics: [
      { t: 0,      instrumental: true },
      { t: 9000,   text: 'I was waiting at the edge of the morning' },
      { t: 13500,  text: 'where the river turns to gold' },
      { t: 18000,  text: 'and the city, half awake, half dreaming' },
      { t: 23000,  text: 'kept the promises it sold' },
      { t: 29500,  instrumental: true },
      { t: 37000,  text: 'Hollow light, hollow light' },
      { t: 41500,  text: 'fold the hours into white' },
      { t: 46500,  text: 'till the silence learns to speak' },
      { t: 51500,  text: 'and the small things make us bright' },
      { t: 58000,  text: 'I was counting all the ways to find you' },
      { t: 63000,  text: "in a language we'd forget" },
      { t: 68000,  text: 'when the morning broke its quiet promise' },
      { t: 73000,  text: 'and the day was not done yet' },
      { t: 80000,  instrumental: true },
      { t: 88000,  text: 'Hollow light, hollow light' },
      { t: 92500,  text: 'fold the hours into white' },
      { t: 97500,  text: 'till the silence learns to speak' },
      { t: 102500, text: 'and the small things make us bright' },
      { t: 110000, text: 'oh, the small things make us bright' },
      { t: 118000, instrumental: true },
    ],
  },
  {
    id: 'track-02',
    title: 'Subtropic',
    artist: 'Marina Reyes',
    album: 'Off-Season',
    year: 2023,
    duration: 196,
    glyph: 'S',
    palette: { bg: [12, 60, 70], bg2: [200, 140, 90], accent: [255, 226, 178] },
    lyrics: [
      { t: 0,      instrumental: true },
      { t: 7000,   text: '설명할 수 없는데' },
      { t: 12000,  text: '온 힘을 다해 난 달려' },
      { t: 17000,  text: '멈춰 서 있고' },
      { t: 22000,  text: '싫지 않아' },
      { t: 29000,  text: 'Subtropic, subtropic' },
      { t: 33500,  text: 'all the storms are out of stock' },
      { t: 38500,  text: 'and the radio keeps playing the slow ones' },
      { t: 43500,  text: 'till the sun forgets the clock' },
      { t: 50000,  instrumental: true },
    ],
  },
  {
    id: 'track-03',
    title: 'Quiet Rooms',
    artist: 'Gabriel Stein',
    album: 'A Map of Small Hours',
    year: 2025,
    duration: 244,
    glyph: 'Q',
    palette: { bg: [20, 22, 28], bg2: [70, 78, 110], accent: [200, 220, 255] },
    lyrics: [
      { t: 0,      instrumental: true },
      { t: 8000,   text: '今や共犯 さ 天の存在もほら' },
      { t: 14000,  text: 'いざ forever ever ever' },
      { t: 19000,  text: '狂って hey kids!! 閉ざした' },
      { t: 24000,  text: '昨日を照らして' },
      { t: 30000,  text: '行き場ない衝動' },
      { t: 35000,  text: '狂って hey kids!! 戻れない' },
      { t: 40000,  text: '場所を探して' },
      { t: 47000,  instrumental: true },
    ],
  },
];
